version: '3.9'
services:

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQ_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql  
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - 8080:80
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./app:/var/www
    depends_on:
      - database

  phpma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1     
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 100M
    ports:
      - 8899:80





        





                  
  
  

